services:
  db:
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    image: mysql:lts
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-storage-engine=InnoDB
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: test_test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    healthcheck:
      test: mysqladmin ping
      start_period: 5s

  app:
    build: .
    command: gunicorn -b 0.0.0.0:8000 league_manager.wsgi
    labels:
      - traefik.http.routers.${SERVICE_NAME}.tls=true
      - traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_HOST}`)
      - traefik.http.routers.${SERVICE_NAME}.tls.certresolver=letsencryptdnsresolver
      - traefik.http.routers.${SERVICE_NAME}_local_qualified.rule=Host(`${SERVICE_NAME}.${LOCAL_HOSTNAME}`)
      - traefik.http.routers.${SERVICE_NAME}_local_qualified.entrypoints=web
    environment:
      MYSQL_HOST: db
      MYSQL_DB_NAME: test_test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      DJANGO_SETTINGS_MODULE: settings.dev
    depends_on:
      db:
        condition: service_healthy

