name: 🏗️🧪🚀 Build, Test and Deploy everything

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  security-events: write

jobs:
  build-test-django:
    uses: ./.github/workflows/part_build_test.yaml
    secrets: inherit

  build-test-scorecard:
    uses: ./.github/workflows/part_node_test.yaml
    secrets: inherit
    with:
      project: scorecard

  build-test-liveticker:
    uses: ./.github/workflows/part_node_test.yaml
    secrets: inherit
    with:
      project: liveticker

  build-passcheck:
    uses: ./.github/workflows/part_node_build.yaml
    secrets: inherit
    with:
      project: passcheck

  deploy-fe:
    needs:
      - build-test-django
      - build-test-scorecard
      - build-test-liveticker
      - build-passcheck
    secrets: inherit
    uses: ./.github/workflows/part_docker_push.yaml
    with:
      image_name: leaguesphere/frontend
      dockerfile: container/nginx.Dockerfile
      publish: true
      version: "${{ github.ref_name }}"

  deploy-be:
    needs:
      - build-test-django
    secrets: inherit
    uses: ./.github/workflows/part_docker_push.yaml
    with:
      image_name: leaguesphere/backend
      test_command: gunicorn -b 0.0.0.0:8000 league_manager.wsgi
      publish: true
      dockerfile: container/app.Dockerfile
      version: "${{ github.ref_name }}"
