name: 🏗️🧪🚀 Build, Test and Deploy everything

on:
  push:
    branches: [ master ]

jobs:
  build-test:
    uses: ./.github/workflows/part_build_test.yaml

  build-test-scorecard:
    uses: ./.github/workflows/part_node_test.yaml
    secrets: inherit
    with:
      project: scorecard

  build-test-liveticker:
    uses: ./.github/workflows/part_node_test.yaml
    secrets: inherit
    with:
      project: liveticker

  build-passcheck:
    uses: ./.github/workflows/part_node_build.yaml
    secrets: inherit
    with:
      project: passcheck

  deploy-fe:
    needs:
      - build-test
      - build-test-scorecard
      - build-test-liveticker
    secrets: inherit
    uses: ./.github/workflows/part_docker_push.yaml
    with:
      image_name: league-manager_frontend
      dockerfile: container/nginx.Dockerfile

  deploy-be:
    needs:
      - build-test
      - build-test-scorecard
      - build-test-liveticker
    secrets: inherit
    uses: ./.github/workflows/part_docker_push.yaml
    with:
      image_name: league-manager_backend
      dockerfile: container/app.Dockerfile
