# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint all projects

on:
  push:
  pull_request:

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ESLint config
        run: |
          cat <<EOL > .eslintrc.js
          module.exports = {
            root: true,
            parser: "@typescript-eslint/parser",
            parserOptions: {
              ecmaVersion: 2020,
              sourceType: "module",
              ecmaFeatures: {
                jsx: true,
              },
            },
            settings: {
              react: {
                version: "detect",
              },
            },
            env: {
              browser: true,
              es6: true,
              node: true,
            },
            plugins: ["@typescript-eslint", "react", "react-hooks", "prettier"],
            extends: [
              "eslint:recommended",
              "plugin:@typescript-eslint/recommended",
              "plugin:react/recommended",
              "plugin:react-hooks/recommended",
              "plugin:prettier/recommended"
            ],
            rules: {
              "prettier/prettier": "warn",
              "react/prop-types": "off",
              "@typescript-eslint/explicit-module-boundary-types": "off",
              "@typescript-eslint/no-unused-vars": ["warn", { "argsIgnorePattern": "^_" }],
              "react/react-in-jsx-scope": "off",
            },
            overrides: [
              {
                files: ["*.ts", "*.tsx"],
                extends: ["plugin:@typescript-eslint/recommended"],
              },
            ],
          };
          EOL

      - name: Install ESLint
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@3.1.0
          npm install @typescript-eslint/eslint-plugin@latest
          npm install eslint-plugin-react@latest
          npm install eslint-plugin-react-hooks@latest
          npm install eslint-plugin-prettier@latest
          npm install prettier 
          npm install eslint-config-prettier
      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: "true"
        run: npx eslint .
          --config .eslintrc.js
          --ext .js,.jsx,.ts,.tsx
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true