name: 🟢🏗️🧪📊 Build & run node tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        description: The project to build
        type: string

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4
      - name: 🟢⚙️ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.project }}/package.json
      - name: 🔍 Run eslint ${{ inputs.project }}
        run: |
          npm ci
          npm run eslint:json
          npm run eslint:sarif
      - name: 👷 Building ${{ inputs.project }}
        run: npm run build > typescript.log
      - name: 🔍📝 Annotate Code Linting Results
        uses: DerLev/eslint-annotations@v2
        with:
          eslint-report: ${{ inputs.project }}/js-lint-results-${{ inputs.project }}.json
          typescript-log: ${{ inputs.project }}/typescript.log
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ inputs.project }}/js-lint-results-${{ inputs.project }}.sarif
          wait-for-processing: true