name: 🟢🏗️🧪📊 Build & run node tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        description: The project to build
        type: string
      report:
        required: false
        default: true
        description: Whether to generate the report
        type: boolean

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4
      - name: 🟢⚙️ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.project }}/package.json
      - name: 📊✅ ${{ inputs.project }} Test report
        if: ${{ inputs.report }}
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ${{ inputs.project }}
          test-script: npm run jest
          custom-title: Report for ${{ inputs.project }}
      - name: ✅ ${{ inputs.project }} Tests
        if: ${{ ! inputs.report }}
        run: |
          npm ci
          npm run jest
      - name: ✅ ${{ inputs.project }} Eslint
        run: npm run eslint:json
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: DerLev/eslint-annotations@v2
        with:
          eslint-report: /tmp/eslint/js-lint-results-${{ inputs.project }}.json
      - name: 👷 ${{ inputs.project }} Build
        run: npm run build
