name: 🟢🏗️🧪📊 Build and run node tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        description: The project to build
        type: string

permissions:
  contents: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4
      - name: 🟢⚙️ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.project }}/package.json
      - name: 📊✅ ${{ inputs.project }} Test report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ${{ inputs.project }}
          test-script: npm run jest
          custom-title: Report for ${{ inputs.project }}

