name: 🟢🏗️🧪📊 Build & run node tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        description: The project to build
        type: string

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4
      - name: 🟢⚙️ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.project }}/package.json
      - name: ✅ ${{ inputs.project }} Eslint
        run: |
          npm ci
          npm run eslint:json
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v3
        with:
          report-json: /tmp/eslint/js-lint-results-${{ inputs.project }}.json
      - name: 👷 ${{ inputs.project }} Build
        run: npm run build
