name: Build and run node tests

on:
  workflow_call:
    inputs:
      project:
        required: true
        description: The project to build
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ${{ inputs.project }}/package.json
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run jest
      - run: ls
      - run: ls ..
      - name: ${{ inputs.project }} Test report
        uses: MishaKav/jest-coverage-comment@main
        with:
          junitxml-path: ./${{ inputs.project }}/junit.xml
          junitxml-title: Test report
          coverage-summary-path: ./${{ inputs.project }}/coverage/coverage-final.json
